# Generated by Django 4.1.4 on 2022-12-20 16:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_alter_qrcollection_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcollection',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
